# Generated by Django 6.1.1 on 2026-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_age_patient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='passward',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
